name: Build
on:
  workflow_dispatch:
      inputs:
        package_name:
          description: "Package name of the game:"
          required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: |
        ls -l
        pwd
        cd /home/runner/work/VirtualXposed/VirtualXposed/VirtualApp && chmod +x ./gradlew
        cd /home/runner/work/VirtualXposed/VirtualXposed/VirtualApp && ./gradlew assembleRelease
    - uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: /home/runner/work/VirtualXposed/VirtualXposed/VirtualApp/app/build/outputs/apk/release/*.apk
        
