name: Build
on:
  workflow_dispatch:
      inputs:
        package_name:
          description: "Package name of the game:"
          required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: gradle
    - run: |
        cd VirtualApp && chmod +x ./gradlew
        cd VirtualApp && ./gradlew assembleRelease
    - uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: VirtualApp/app/build/outputs/apk/release/*.apk
        
